### ISSUE TITLE
Install instuctions are not working with TextMate 2.0

### ISSUE THREAD

**Issue by usmanismail** [kevinweil/protobuf.tmbundle#1]
I get the following error when I issue the osascript command

23:37: syntax error: A identifier can’t go after this identifier. (-2740)

**Comment by novabyte** [comment]
@usmanismail If you copy the Protobuf.tmbundle to the `~/Library/Application Support/TextMate/Managed/Bundles/` folder it'll be auto-detected at the next start up.

This is all with Version 2.0 (9292).

Hope this helps.
